name: "Base Workflow"

on:
  push:
    branches:
      - 'main'
      - 'staging'
      - 'dev/**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  settings-sync:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Initialize"
        run: "sudo snap install deno"
      - name: "Sync Settings"
        run: "bash dev/Z99.gh_settings_sync.sh"
        env:
          GH_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Validate"
        run: "bash dev/A0.all.sh"
