name: "Repo Settings Sync"

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  settings-sync:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Settings Sync"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Initialize"
        run: "sudo snap install deno"
      - name: "Call Script"
        run: "bash dev/upstream_refresh_github.sh"
        env:
          GH_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}