name: "Simple Validate"

on:
  push:
    branches:
      - 'main'
      - 'staging'
      - 'dev/**'

jobs:
  settings-sync:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: "Validate"
        run: "bash dev/A0.all.sh"
